version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_ACCOUNT_ID, $AWS_DEFAULT_REGION, $REPOSITORY_URI, $CODEBUILD_RESOLVED_SOURCE_VERSION, $REPOSITORY_NAME
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - FULL_REPOSITORY_NAME=$REPOSITORY_URI/$REPOSITORY_NAME

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $FULL_REPOSITORY_NAME:latest .
      - docker tag $FULL_REPOSITORY_NAME:latest $FULL_REPOSITORY_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $FULL_REPOSITORY_NAME:latest
      - docker push $FULL_REPOSITORY_NAME:$IMAGE_TAG
      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $FULL_REPOSITORY_NAME:$IMAGE_TAG > imagedefinitions.json
  artifacts:
      files: imagedefinitions.json
